name: SAST - Semgrep
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  semgrep:
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@v4
      - run: >-
          semgrep scan --config auto --error
